// source: com/reports/v1/filter.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.com.reports.v1.Filter');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.reports.v1.Filter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.reports.v1.Filter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.reports.v1.Filter.displayName = 'proto.com.reports.v1.Filter';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.reports.v1.Filter.prototype.toObject = function(opt_includeInstance) {
  return proto.com.reports.v1.Filter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.reports.v1.Filter} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.reports.v1.Filter.toObject = function(includeInstance, msg) {
  var f, obj = {
    userId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    eventIds: jspb.Message.getFieldWithDefault(msg, 2, ""),
    minDateOfOrder: jspb.Message.getFieldWithDefault(msg, 3, ""),
    maxDateOfOrder: jspb.Message.getFieldWithDefault(msg, 4, ""),
    minDateOfAttendance: jspb.Message.getFieldWithDefault(msg, 5, ""),
    maxDateOfAttendance: jspb.Message.getFieldWithDefault(msg, 6, ""),
    currency: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.reports.v1.Filter}
 */
proto.com.reports.v1.Filter.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.reports.v1.Filter;
  return proto.com.reports.v1.Filter.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.reports.v1.Filter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.reports.v1.Filter}
 */
proto.com.reports.v1.Filter.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEventIds(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMinDateOfOrder(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMaxDateOfOrder(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMinDateOfAttendance(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setMaxDateOfAttendance(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrency(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.reports.v1.Filter.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.reports.v1.Filter.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.reports.v1.Filter} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.reports.v1.Filter.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEventIds();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMinDateOfOrder();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getMaxDateOfOrder();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMinDateOfAttendance();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getMaxDateOfAttendance();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getCurrency();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional string user_id = 1;
 * @return {string}
 */
proto.com.reports.v1.Filter.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.reports.v1.Filter} returns this
 */
proto.com.reports.v1.Filter.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string event_ids = 2;
 * @return {string}
 */
proto.com.reports.v1.Filter.prototype.getEventIds = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.reports.v1.Filter} returns this
 */
proto.com.reports.v1.Filter.prototype.setEventIds = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string min_date_of_order = 3;
 * @return {string}
 */
proto.com.reports.v1.Filter.prototype.getMinDateOfOrder = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.reports.v1.Filter} returns this
 */
proto.com.reports.v1.Filter.prototype.setMinDateOfOrder = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string max_date_of_order = 4;
 * @return {string}
 */
proto.com.reports.v1.Filter.prototype.getMaxDateOfOrder = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.reports.v1.Filter} returns this
 */
proto.com.reports.v1.Filter.prototype.setMaxDateOfOrder = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string min_date_of_attendance = 5;
 * @return {string}
 */
proto.com.reports.v1.Filter.prototype.getMinDateOfAttendance = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.reports.v1.Filter} returns this
 */
proto.com.reports.v1.Filter.prototype.setMinDateOfAttendance = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string max_date_of_attendance = 6;
 * @return {string}
 */
proto.com.reports.v1.Filter.prototype.getMaxDateOfAttendance = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.reports.v1.Filter} returns this
 */
proto.com.reports.v1.Filter.prototype.setMaxDateOfAttendance = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string currency = 7;
 * @return {string}
 */
proto.com.reports.v1.Filter.prototype.getCurrency = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.reports.v1.Filter} returns this
 */
proto.com.reports.v1.Filter.prototype.setCurrency = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


